version: "3.7"
services:
  postgres:
    image: postgres
    restart: always
    container_name: streamed_order_viewer_db
    hostname: postgres
    env_file:
      - .env
    ports:
      - "5435:5435"